name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'  
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  #auto_route: ^7.8.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

dev_dependencies:
  #auto_route_generator: ^7.3.1
  #build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/